title: Jorin's webbed sight
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

collections_dir: collection
collections:
  ramble:
    output: true
    title: Jorin's Rambles
    short_title: Rambles
    description: blog
    group_field: null
    sort_field: date

  grimoire:
    output: true
    title: The Grimoire of Jorin
    short_title: Grimoire
    description: personal wiki
    group_field: tags
    sort_field: title

  machination:
    output: true
    title: Jorin's Machinations
    short_title: Machinations
    description: project logs and documentation
    group_field: tags
    sort_field: last_updated

pagination:
  enabled: true
  per_page: 10
  permalink: /:year/:month/:title:output_ext
  title: ' - page :num'
  limit: 0
  sort_field: date
  sort_reverse: true

autopages:
  enabled: true
  collections:
    layouts:
      - collection.html
    title: :coll
    permalink: /:coll
    silent: false
    slugify:
      mode: default
      case: true

  tags:
    layouts:
      - tag.html
    title: "':tag' in :coll"
    permalink: /:coll/:tag
    silent: false
    slugify:
      mode: default
      case: true

defaults:
  -
    scope:
      path: ''
      type: ramble
    values:
      layout: post
  -
    scope:
      path: ''
      type: grimoire
    values:
      layout: grimoire
  -
    scope:
      path: ''
      type: machination
    values:
      layout: machination

minima:
  skin: melatonin

include:
  - .well-known

links:
  -
    title: 'Twitter'
    text: '@YawningJorin'
    href: 'https://twitter.com/YawningJorin'
  -
    title: 'SoundCloud'
    text: 'Yawning Girl'
    href: 'https://soundcloud.com/yawninggirl'
  -
    title: 'Bandcamp'
    text: 'Yawning Girl'
    href: 'https://yawninggirl.bandcamp.com'
  -
    title: 'GitHub'
    href: 'https://github.com/jorins'
