title: Jorin
description: You have reached Jorin's webbed sight
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

minima:
  skin: melatonin

include:
  - .well-known
